#---variables de api_dev
tower_base_url: "http://172.18.0.5:8052"
tower_token: "T3qIBMvwZMS9321AL39Dlm66HeB3iX"

#---variables comandos os
accionjtp:
  inventarioid: 2
  trabajoid: 76
  credemciales: "[1]"
  idcrqinc: "{{idcrqinc}}"
  team_id: 1
  tarea: "Proceso_LVM"
  demora: 2
  reintentos: 9999